config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/athenarc/EOSCF-Provider-Insights:
      branch: master
      repo: https://github.com/athenarc/EOSCF-Provider-Insights.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/athenarc/EOSCF-Provider-Insights git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-asparagus-squirt.sh
        container: qc.acc_dorky-apricot-caracal
  QC.Doc:
    repos:
      github.com/athenarc/EOSCF-Provider-Insights find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-wheat-buzzard.sh
        container: qc.doc_queasy-gold-emu
      github.com/athenarc/EOSCF-Provider-Insights git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-alizarin-bracke.sh
        container: qc.doc_bluesy-purple-mandrill
      github.com/athenarc/EOSCF-Provider-Insights markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-pumpkin-zebra.sh
        container: qc.doc_scummy-buff-bloodhound
  QC.Lic:
    repos:
      github.com/athenarc/EOSCF-Provider-Insights licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-linen-seahorse.sh
        container: qc.lic_lumpy-jade-stingray
  QC.Met:
    repos:
      github.com/athenarc/EOSCF-Provider-Insights cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-smalt-ferret.sh
        container: qc.met_muggy-magnolia-chamois
  QC.Sec:
    repos:
      github.com/athenarc/EOSCF-Provider-Insights bandit:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-ecru-cichlid.sh
        container: qc.sec_crabby-purple-clam
  QC.Sty:
    repos:
      github.com/athenarc/EOSCF-Provider-Insights flake8:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-turquoise-millipede.sh
        container: qc.sty_geeky-pink-russel
      github.com/athenarc/EOSCF-Provider-Insights hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-charcoal-shrimp.sh
        container: qc.sty_homey-fuchsia-starfish
  QC.Ver:
    repos:
      github.com/athenarc/EOSCF-Provider-Insights get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-magenta-quail.sh
        container: qc.ver_crabby-teal-moth
timeout: 5400
